name: Validate DFIQ YAML

on:
  [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry add yamale
    - name: Validate Scenarios YAML
      run: |
        poetry run yamale -s utils/scenario_spec.yaml ./data/scenarios
        poetry run yamale -s utils/facet_spec.yaml ./data/facets
        poetry run yamale -s utils/question_spec.yaml ./data/questions
        poetry run yamale -s utils/approach_spec.yaml ./data/approaches
